apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dinov3-api-hpa
  namespace: dinov3
  labels:
    app.kubernetes.io/name: dinov3
    app.kubernetes.io/component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dinov3-api
  
  minReplicas: 2
  maxReplicas: 10
  
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # GPU utilization (if supported by cluster)
  - type: Resource
    resource:
      name: nvidia.com/gpu
      target:
        type: Utilization
        averageUtilization: 75
  
  # Custom metrics (requires Prometheus adapter)
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "10"
  
  - type: Pods
    pods:
      metric:
        name: inference_queue_length
      target:
        type: AverageValue
        averageValue: "5"
  
  # Scale-down behavior (conservative)
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    
    # Scale-up behavior (more aggressive)
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
# Vertical Pod Autoscaler (optional)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dinov3-api-vpa
  namespace: dinov3
  labels:
    app.kubernetes.io/name: dinov3
    app.kubernetes.io/component: autoscaler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dinov3-api
  
  updatePolicy:
    updateMode: "Auto"  # Options: Off, Auto, RecreatePods, Initial
  
  resourcePolicy:
    containerPolicies:
    - containerName: dinov3-api
      minAllowed:
        cpu: 1
        memory: 4Gi
      maxAllowed:
        cpu: 8
        memory: 32Gi
      controlledResources:
      - cpu
      - memory